make update

diff --git a/13-master/Dockerfile b/13-master/Dockerfile
--- a/13-master/Dockerfile
+++ b/13-master/Dockerfile
@@ -62,7 +62,7 @@ RUN set -ex \
 # sfcgal
 ENV SFCGAL_VERSION master
 #current:
-#ENV SFCGAL_GIT_HASH 7d6bd802e7899a16b59277d6fb8204b55102c64d
+#ENV SFCGAL_GIT_HASH cf03cf7869778f69f8baddfbd73415bf99499663
 #reverted for the last working version
 ENV SFCGAL_GIT_HASH e1f5cd801f8796ddb442c06c11ce8c30a7eed2c5
 
@@ -82,7 +82,7 @@ RUN set -ex \
 
 # proj
 ENV PROJ_VERSION master
-ENV PROJ_GIT_HASH c6c2a3b22ddef30a29cfc48ca810ee1a54385242
+ENV PROJ_GIT_HASH 4ecb0abb8c3d3f5efcdd79643bc3302aa9bc6d1e
 
 RUN set -ex \
     && cd /usr/src \
@@ -98,7 +98,7 @@ RUN set -ex \
 
 # geos
 ENV GEOS_VERSION master
-ENV GEOS_GIT_HASH e1d8471e2a9f579ebfbf6f49b3e37bd6eaad8565
+ENV GEOS_GIT_HASH 70d2111bd66ea848809e5738896256199d9a7cba
 
 RUN set -ex \
     && cd /usr/src \
@@ -115,7 +115,7 @@ RUN set -ex \
 
 # gdal
 ENV GDAL_VERSION master
-ENV GDAL_GIT_HASH 2618ede82419c09a2fd313d9cccfaf9f9acf93bc
+ENV GDAL_GIT_HASH 642888ff9f9e1814f962d4cff5082257a47e84fd
 
 RUN set -ex \
     && cd /usr/src \
@@ -180,10 +180,10 @@ RUN set -ex \
 
 COPY --from=builder /usr/local /usr/local
 
-#ENV SFCGAL_GIT_HASH 7d6bd802e7899a16b59277d6fb8204b55102c64d
-ENV PROJ_GIT_HASH c6c2a3b22ddef30a29cfc48ca810ee1a54385242
-ENV GEOS_GIT_HASH e1d8471e2a9f579ebfbf6f49b3e37bd6eaad8565
-ENV GDAL_GIT_HASH 2618ede82419c09a2fd313d9cccfaf9f9acf93bc
+#ENV SFCGAL_GIT_HASH cf03cf7869778f69f8baddfbd73415bf99499663
+ENV PROJ_GIT_HASH 4ecb0abb8c3d3f5efcdd79643bc3302aa9bc6d1e
+ENV GEOS_GIT_HASH 70d2111bd66ea848809e5738896256199d9a7cba
+ENV GDAL_GIT_HASH 642888ff9f9e1814f962d4cff5082257a47e84fd
 
 # Minimal command line test.
 RUN set -ex \
@@ -195,9 +195,13 @@ RUN set -ex \
     && proj \
     && sfcgal-config --version
 
+# Testing ogr2ogr PostgreSQL driver.
+RUN ogr2ogr --formats | grep -q "PostgreSQL/PostGIS" && exit 0 \
+    || echo "ogr2ogr missing PostgreSQL driver" && exit 1
+
 # install postgis
 ENV POSTGIS_VERSION master
-ENV POSTGIS_GIT_HASH b67f6c80f24edb57fa223a2065c2255bbb346cef
+ENV POSTGIS_GIT_HASH 4fa57df0b3bd726346e1fd272921a29ab888b55f
 
 RUN set -ex \
     && apt-get update \
